In [10]:
import pandas as pd
import os
klasor_yolu = r"C:\Users\Tugce\OneDrive\Masaüstü\Proje_Omnichannel_DW" 

dosyalar= [
    "distribution_centers.csv",
    "products_old.csv",
    "users_old.csv",
    "orders.csv",
    "order_items.csv",
    "inventory_items_old.csv",
    "events_old.csv"]

for dosya in dosyalar:
    tam_yol = os.path.join(klasor_yolu, dosya)
    if os.path.exists(tam_yol):
        df_ornek =pd.read_csv(tam_yol, nrows=5)
        print(df_ornek,5)
    else:
        print(f" {dosya} bulunamadı\n")

   id            name  latitude  longitude
0   1      Memphis TN   35.1174   -89.9711
1   2      Chicago IL   41.8369   -87.6847
2   3      Houston TX   29.7604   -95.3698
3   4  Los Angeles CA   34.0500  -118.2500
4   5  New Orleans LA   29.9500   -90.0667 5
      id     cost     category  \
0  13842  2.51875  Accessories
1  13928  2.33835  Accessories
2  14115  4.87956  Accessories
3  14157  4.64877  Accessories
4  14273  6.50793  Accessories

                                                name brand  retail_price  \
0   Low Profile Dyed Cotton Twill Cap - Navy W39S55D    MG          6.25
1  Low Profile Dyed Cotton Twill Cap - Putty W39S55D    MG          5.95
2       Enzyme Regular Solid Army Caps-Black W35S45D    MG         10.99
3  Enzyme Regular Solid Army Caps-Olive W35S45D (...    MG         10.99
4              Washed Canvas Ivy Cap - Black W11S64C    MG         15.99

  department                               sku  distribution_center_id
0      Women  EBD58B8A3F1D72F4206201DA62FB1204                       1
1      Women  2EAC42424D12436BDD6A5B8A88480CC3                       1
2      Women  EE364229B2791D1EF9355708EFF0BA34                       1
3      Women  00BD13095D06C20B11A2993CA419D16B                       1
4      Women  F531DC20FDE20B7ADF3A73F52B71D0AF                       1   5
      id   first_name last_name                         email  age gender  \
0    201     Jennifer     Curry     jennifercurry@example.net   33      F
1   1379        Paula    Kelley       paulakelley@example.net   16      F
2  11964       Ashley     James       ashleyjames@example.net   24      F
3  12069  Christopher     Clark  christopherclark@example.net   37      M
4  12873       Dillon    Brooks      dillonbrooks@example.net   62      M

  state                street_address postal_code  city country  latitude  \
0  Acre             193 Morales Ferry   69980-000   NaN  Brasil -8.065346
1  Acre  69002 Bradley Coves Apt. 702   69980-000   NaN  Brasil -8.065346
2  Acre    02164 Morgan Rue Suite 663   69980-000   NaN  Brasil -8.065346
3  Acre  70030 Ashley River Suite 364   69980-000   NaN  Brasil -8.065346
4  Acre           626 Kathleen Valley   69980-000   NaN  Brasil -8.065346

   longitude traffic_source               created_at
0 -72.870949        Organic  2024-05-16 03:40:00 UTC
1 -72.870949         Search  2021-04-16 10:57:00 UTC
2 -72.870949         Search  2021-06-19 03:40:00 UTC
3 -72.870949         Search  2019-05-08 09:16:00 UTC
4 -72.870949         Search  2023-09-26 17:15:00 UTC   5
   order_id  user_id     status gender               created_at  returned_at  \
0         9       10  Cancelled      F  2021-12-12 05:47:00 UTC          NaN
1        37       31  Cancelled      F  2021-01-15 06:22:00 UTC          NaN
2        44       37  Cancelled      F  2023-12-07 04:25:00 UTC          NaN
3        56       47  Cancelled      F  2024-04-20 13:21:00 UTC          NaN
4        65       51  Cancelled      F  2022-08-08 04:57:00 UTC          NaN

   shipped_at  delivered_at  num_of_item
0         NaN           NaN            1
1         NaN           NaN            2
2         NaN           NaN            1
3         NaN           NaN            2
4         NaN           NaN            1   5
       id  order_id  user_id  product_id  inventory_item_id     status  \
0   89648     61749    49362       14235             241929   Complete
1  137052     94346    75385       14159             369603  Cancelled
2   22367     15431    12367       14159              60413   Complete
3   40738     28141    22516       14159             109957   Complete
4   58354     40241    32110       14159             157594   Complete

                created_at               shipped_at             delivered_at  \
0  2019-08-04 14:26:00 UTC  2019-08-01 04:33:00 UTC  2019-08-02 09:24:00 UTC
1  2024-08-22 16:48:19 UTC                      NaN                      NaN
2  2020-05-29 12:02:20 UTC  2020-05-29 03:43:00 UTC  2020-05-29 14:09:00 UTC
3  2021-02-26 10:59:47 UTC  2021-02-28 09:26:00 UTC  2021-03-01 18:44:00 UTC
4  2022-12-15 14:20:40 UTC  2022-12-15 05:35:00 UTC  2022-12-17 16:10:00 UTC

   returned_at  sale_price
0          NaN        0.02
1          NaN        0.49
2          NaN        0.49
3          NaN        0.49
4          NaN        0.49   5
       id  product_id               created_at                  sold_at  \
0   29638       13844  2022-11-20 12:18:28 UTC  2022-12-29 13:50:28 UTC
1   29639       13844  2020-03-16 17:29:00 UTC                      NaN
2  110316       13844  2021-10-31 17:46:22 UTC  2021-11-19 05:18:22 UTC
3  110317       13844  2024-01-27 09:16:00 UTC                      NaN
4  340407       13844  2022-12-19 01:39:00 UTC  2023-01-24 00:10:00 UTC

      cost product_category            product_name       product_brand  \
0  2.76804      Accessories  (ONE) 1 Satin Headband  Funny Girl Designs
1  2.76804      Accessories  (ONE) 1 Satin Headband  Funny Girl Designs
2  2.76804      Accessories  (ONE) 1 Satin Headband  Funny Girl Designs
3  2.76804      Accessories  (ONE) 1 Satin Headband  Funny Girl Designs
4  2.76804      Accessories  (ONE) 1 Satin Headband  Funny Girl Designs

   product_retail_price product_department                       product_sku  \
0                  6.99              Women  2A3E953A5E3D81E67945BCE5519F84C8
1                  6.99              Women  2A3E953A5E3D81E67945BCE5519F84C8
2                  6.99              Women  2A3E953A5E3D81E67945BCE5519F84C8
3                  6.99              Women  2A3E953A5E3D81E67945BCE5519F84C8
4                  6.99              Women  2A3E953A5E3D81E67945BCE5519F84C8

   product_distribution_center_id
0                               7
1                               7
2                               7
3                               7
4                               7   5
        id  user_id  sequence_number                            session_id  \
0  1936238      NaN                3  e9463c96-8d2b-409f-b909-2a7df2ed521e
1  2316331      NaN                3  38568fb8-47ac-48e9-9d91-33e900e7cbed
2  1974374      NaN                3  3c78decc-4e06-4e22-aa15-310c507b55d5
3  1401565      NaN                3  c9762f1f-05a3-4663-88f0-9bf77d7a8184
4  2007567      NaN                3  4e450337-9c21-4283-acb2-13c718b2d7e5

                created_at       ip_address       city      state postal_code  \
0  2020-10-15 18:53:00 UTC   187.102.253.91    Sapporo   Hokkaido    005-0041
1  2019-10-04 05:48:00 UTC  105.253.208.106  São Paulo  São Paulo   02675-031
2  2024-08-26 12:27:00 UTC      48.234.3.31  São Paulo  São Paulo   02675-031
3  2021-02-13 04:18:00 UTC   28.130.161.246  São Paulo  São Paulo   02675-031
4  2023-01-22 18:17:00 UTC   103.204.10.157  São Paulo  São Paulo   02675-031

   browser traffic_source      uri event_type
0   Chrome          Email  /cancel     cancel
1   Safari          Email  /cancel     cancel
2  Firefox          Email  /cancel     cancel
3   Chrome          Email  /cancel     cancel
4   Chrome          Email  /cancel     cancel   5

In [13]:
orders=pd.read_csv(os.path.join(klasor_yolu, "orders.csv"))
orders.head()

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item
0,9,10,Cancelled,F,2021-12-12 05:47:00 UTC,NaN,NaN,NaN,1
1,37,31,Cancelled,F,2021-01-15 06:22:00 UTC,NaN,NaN,NaN,2
2,44,37,Cancelled,F,2023-12-07 04:25:00 UTC,NaN,NaN,NaN,1
3,56,47,Cancelled,F,2024-04-20 13:21:00 UTC,NaN,NaN,NaN,2
4,65,51,Cancelled,F,2022-08-08 04:57:00 UTC,NaN,NaN,NaN,1

In [15]:
order_items=pd.read_csv(os.path.join(klasor_yolu, "order_items.csv"))
order_items.head(3)

,id,order_id,user_id,product_id,inventory_item_id,status,created_at,shipped_at,delivered_at,returned_at,sale_price
0,89648,61749,49362,14235,241929,Complete,2019-08-04 14:26:00 UTC,2019-08-01 04:33:00 UTC,2019-08-02 09:24:00 UTC,NaN,0.02
1,137052,94346,75385,14159,369603,Cancelled,2024-08-22 16:48:19 UTC,NaN,NaN,NaN,0.49
2,22367,15431,12367,14159,60413,Complete,2020-05-29 12:02:20 UTC,2020-05-29 03:43:00 UTC,2020-05-29 14:09:00 UTC,NaN,0.49

In [16]:
products = pd.read_csv(os.path.join(klasor_yolu, "products_old.csv"))
products.head(3)

,id,cost,category,name,brand,retail_price,department,sku,distribution_center_id
0,13842,2.51875,Accessories,Low Profile Dyed Cotton Twill Cap - Navy W39S55D,MG,6.25,Women,EBD58B8A3F1D72F4206201DA62FB1204,1
1,13928,2.33835,Accessories,Low Profile Dyed Cotton Twill Cap - Putty W39S55D,MG,5.95,Women,2EAC42424D12436BDD6A5B8A88480CC3,1
2,14115,4.87956,Accessories,Enzyme Regular Solid Army Caps-Black W35S45D,MG,10.99,Women,EE364229B2791D1EF9355708EFF0BA34,1

In [22]:
order_items['created_at'] =pd.to_datetime(order_items['created_at'], errors='coerce',utc=True)
order_items['year_month'] =order_items['created_at'].dt.to_period('M').astype(str)
print(order_items.dtypes)

id                                 int64
order_id                           int64
user_id                            int64
product_id                         int64
inventory_item_id                  int64
status                            object
created_at           datetime64[ns, UTC]
shipped_at                        object
delivered_at                      object
returned_at                       object
sale_price                       float64
year_month                        object
dtype: object

In [ ]:
# TABLO 1: AYLIK BÜTÇE VE MALİYET HEDEFLERİ (monthly_budget_targets.csv)

In [29]:
#products tablosundaki 'id' sütununun adını 'product_id' yapıyoruz
products_temiz =products[['id','department', 'category', 'cost']].rename(columns={'id': 'product_id'})
birlesik_tablo =pd.merge(order_items, products_temiz, on='product_id')
print(birlesik_tablo)
birleşik_tablo.info()

            id  order_id  user_id  product_id  inventory_item_id     status  \
0        89648     61749    49362       14235             241929   Complete
1       137052     94346    75385       14159             369603  Cancelled
2        22367     15431    12367       14159              60413   Complete
3        40738     28141    22516       14159             109957   Complete
4        58354     40241    32110       14159             157594   Complete
...        ...       ...      ...         ...                ...        ...
181750  111901     77056    61515       23546             302018    Shipped
181751  139120     95782    76568       24447             375211    Shipped
181752  153067    105314    84244       23546             412971    Shipped
181753  176354    121384    97025       23546             475828    Shipped
181754  177145    121931    97488       24447             477978    Shipped

                      created_at               shipped_at  \
0      2019-08-04 14:26:00+00:00  2019-08-01 04:33:00 UTC
1      2024-08-22 16:48:19+00:00                      NaN
2      2020-05-29 12:02:20+00:00  2020-05-29 03:43:00 UTC
3      2021-02-26 10:59:47+00:00  2021-02-28 09:26:00 UTC
4      2022-12-15 14:20:40+00:00  2022-12-15 05:35:00 UTC
...                          ...                      ...
181750 2024-01-20 13:46:15+00:00  2024-01-20 17:08:00 UTC
181751 2023-04-28 04:39:00+00:00  2023-04-28 19:02:00 UTC
181752 2021-07-28 00:06:10+00:00  2021-07-28 17:43:00 UTC
181753 2024-05-17 00:48:14+00:00  2024-05-18 22:53:00 UTC
181754 2022-07-23 01:03:12+00:00  2022-07-23 18:14:00 UTC

                   delivered_at returned_at  sale_price year_month department  \
0       2019-08-02 09:24:00 UTC         NaN        0.02    2019-08      Women
1                           NaN         NaN        0.49    2024-08      Women
2       2020-05-29 14:09:00 UTC         NaN        0.49    2020-05      Women
3       2021-03-01 18:44:00 UTC         NaN        0.49    2021-02      Women
4       2022-12-17 16:10:00 UTC         NaN        0.49    2022-12      Women
...                         ...         ...         ...        ...        ...
181750                      NaN         NaN      999.00    2024-01        Men
181751                      NaN         NaN      999.00    2023-04        Men
181752                      NaN         NaN      999.00    2021-07        Men
181753                      NaN         NaN      999.00    2024-05        Men
181754                      NaN         NaN      999.00    2022-07        Men

                 category        cost
0             Accessories    0.008300
1             Accessories    0.177380
2             Accessories    0.177380
3             Accessories    0.177380
4             Accessories    0.177380
...                   ...         ...
181750             Shorts  482.516999
181751  Outerwear & Coats  404.595001
181752             Shorts  482.516999
181753             Shorts  482.516999
181754  Outerwear & Coats  404.595001

[181755 rows x 15 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181755 entries, 0 to 181754
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id_x               181755 non-null  int64
 1   order_id           181755 non-null  int64
 2   user_id            181755 non-null  int64
 3   product_id         181755 non-null  int64
 4   inventory_item_id  181755 non-null  int64
 5   status             181755 non-null  object
 6   created_at         177062 non-null  datetime64[ns, UTC]
 7   shipped_at         118147 non-null  object
 8   delivered_at       63336 non-null   object
 9   returned_at        18039 non-null   object
 10  sale_price         181755 non-null  float64
 11  year_month         181755 non-null  object
 12  id_y               181755 non-null  int64
 13  cost               181755 non-null  float64
 14  category           181755 non-null  object
 15  department         181755 non-null  object
dtypes: datetime64[ns, UTC](1), float64(2), int64(6), object(7)
memory usage: 22.2+ MB

In [31]:
#Her ay ve kategoride toplam ne kadar satış ve maliyet olmuş topluyoruz (Pivot Table gibi)
aylık_özet=birleşik_tablo.groupby(['year_month','department','category'],
                                  as_index=False).agg({'sale_price':'sum', 'cost':'sum'})
aylık_özet.head()

  year_month department           category  sale_price       cost
0    2019-01        Men        Accessories   22.000000    9.76800
1    2019-01        Men             Active   15.000000    6.16500
2    2019-01        Men  Outerwear & Coats  408.139999  181.08998
3    2019-01        Men              Pants  158.000000   73.66700
4    2019-01        Men              Socks   12.000000    7.24800

In [33]:
#Gerçek satışın %95'i ile %110'u arasında rastgele bir Bütçe Hedefi belirliyoruz
rastgele_oran =np.random.uniform(0.95, 1.10, size=len(aylık_özet))
aylık_özet['budget_revenue_target'] =(aylık_özet['sale_price'] * rastgele_oran).round(2)

In [35]:
#Maliyet limiti ve pazarlama bütçesini de basit birer oranla ekliyoruz
aylık_özet['budget_cost_limit']=(aylık_özet['cost'] * 1.02).round(2)
aylık_özet['marketing_budget_allocated'] =(aylık_özet['budget_revenue_target'] * 0.08).round(2)
budget_df=aylık_özet[['year_month','department', 'category', 'budget_revenue_target', 'budget_cost_limit', 'marketing_budget_allocated']]
budget_df.to_csv(os.path.join(klasor_yolu, "monthly_budget_targets.csv"), index=False)

In [36]:
# 1. Kupon kodlarını ve indirim oranlarını tanımlıyoruz
kupon_kodlari = ['NO_VOUCHER', 'WELCOME10', 'SEASON15', 'VIP25']
olasiliklar   = [0.65, 0.15, 0.12, 0.08] # Toplamı 1.00 (%100) yapıyor
secilen_kuponlar = np.random.choice(kupon_kodlari, size=len(orders), p=olasiliklar)

#Kupon koduna göre indirim oranını eşleştiriyoruz
indirim_sozlugu = {'NO_VOUCHER': 0.0, 'WELCOME10': 0.10, 'SEASON15': 0.15, 'VIP25': 0.25}
indirim_oranlari = pd.Series(secilen_kuponlar).map(indirim_sozlugu)

# Kargo Maliyeti = Sabit 5$ + (Ürün Adedi x 1.25$)
kargo_maliyeti = (5.0 + (orders['num_of_item'] * 1.25)).round(2)
iade_maliyeti = np.where(orders['status'] == 'Returned', kargo_maliyeti, 0.0)
vouchers_shipping_df = pd.DataFrame({
    'order_id': orders['order_id'],
    'voucher_code': secilen_kuponlar,
    'voucher_discount_rate': indirim_oranlari,
    'shipping_cost': kargo_maliyeti,
    'return_logistics_cost': iade_maliyeti
})

vouchers_shipping_df.to_csv(os.path.join(klasor_yolu, "order_vouchers_shipping.csv"), index=False)